export const actions = {
    profile: {
        DATA_FETCHING: "PROFILE_DATA_FETCHING",
        DATA_FETCHED: "PROFILE_DATA_FETCHED",
        DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
        USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
        DATA_UPDATE_ERROR: "PROFILE_DATA_UPDATE_ERROR",
        IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
    },

    blog: {
        DATA_FETCHING: "BLOG_DATA_FETCHING",
        DATA_FETCHED: "BLOG_DATA_FETCHED",
        DATA_RESET_BLOG_BLOG_LIST: "BLOG_LIST_DATA_RESET",
        DATA_FETCH_ERROR: "BLOG_DATA_FETCH_ERROR",
        DATA_CREATED: "BLOG_DATA_CREATED",
        DATA_EDITED: "BLOG_DATA_EDITED",
        POST_DELETED: "BLOG_DATA_DELETED",
    },
    popularBlog: {
        DATA_FETCHING: "POPULAR_BLOG_DATA_FETCHING",
        DATA_FETCHED: "POPULAR_BLOG_DATA_FETCHED",
        DATA_FETCH_ERROR: "POPULAR_BLOG_DATA_FETCH_ERROR",
    },
    favouriteBlog: {
        DATA_FETCHING: "FAVOURITE_BLOG_DATA_FETCHING",
        DATA_FETCHED: "FAVOURITE_BLOG_DATA_FETCHED",
        DATA_FETCH_ERROR: "FAVOURITE_BLOG_DATA_FETCH_ERROR",
    },
    blogDetail: {
        DATA_FETCHING: "BLOG_DETAIL_DATA_FETCHING",
        DATA_FETCHED: "BLOG_DETAIL_DATA_FETCHED",
        DATA_FETCH_ERROR: "BLOG_DETAIL_DATA_FETCH_ERROR",
    }
};